feat(docker): init docker-compose deps
sbine/bdgt pull request #25
Opened 2020-10-04 00:08 UTC by mralanlee

WIP #22

2020-10-04 17:58 UTC, Saibamen requested changes

2020-10-04 17:58 UTC, Saibamen commented on docker-compose.yml
> +    image: php:7.0-apache
Repo uses Laravel 8, so minimum supported PHP version is 7.3

2020-10-04 18:00 UTC, Saibamen commented on docker-compose.yml
> +version: "3.4"
```suggestion
version: "3.8"
```

2020-10-04 18:01 UTC, Saibamen commented on docker-compose.yml
> +    image: php:7.0-apache
```suggestion
    image: php:7.3-apache
```

2020-10-04 22:14 UTC, pfaffenrodt commented
I dont know, if it is already enough, by using blank php image.

use `APACHE_DOCUMENT_ROOT` env variable to point to `/app/public` and not provide two volumes ( looks wrong to me)

I suggest, create a `.docker/php/Dockerfile`.

Nice to have:
* argument to provide userid and groupid of www-data user
* npm via nvm?
* imagick
* supervisor (to boot queue worker)
* crontab
* tinker support

install all packages and NPM via nvm.

2020-10-04 22:41 UTC, mralanlee commented
I was thinking of using another docker-compose file for node (i.e. `docker-compose.node.yml`). It doesn't seem like the project always requires hot reload or watching to occur.

> use APACHE_DOCUMENT_ROOT env variable to point to /app/public and not provide two volumes ( looks wrong to me)

Yeah, it doesn't feel ergonomic to me either. I just wanted to play with it to see how that would go, and hope to get a baseline of something working.

2020-10-05 06:26 UTC, Saibamen commented
> * npm via nvm?

For what? Docker image will be bigger.

But if you want to test Docker images in CI with different NPM versions - it is OK for me

2020-10-05 09:00 UTC, pfaffenrodt commented
> For what? Docker image will be bigger.

Because it is easier to use to install inside php images. nvm script is not that big. It is a suggestion.

2020-10-05 17:53 UTC, mralanlee commented
> I dont know, if it is already enough, by using blank php image.

Maybe I could create an actual base image to pack all the required dependencies to get PHP and Laravel to work, and a base node project to tailor to the requirements a bit more. Thoughts?

2020-10-06 04:11 UTC, sbine commented
@mralanlee I just merged #48 which was a separate first pass at this, but I would love to keep iterating on it with you–it could still be improved by switching out MySQL for MariaDB and adding SSL. No need to move forward with Apache though, I'm just going to move bdgt production over to Nginx.

2020-10-06 04:13 UTC, mralanlee commented
Sounds good. Let me pull those changes off of that and work from that.

2020-10-06 10:24 UTC, pfaffenrodt commented on docker/php/Dockerfile
> +RUN wget https://getcomposer.org/composer-stable.phar -O /usr/local/bin/composer && chmod +x /usr/local/bin/composer
```suggestion
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN mkdir -p /var/www/.composer && chown -R www-data: /var/www/.composer && chmod -R u+w /var/www/.composer
```

2020-10-06 14:51 UTC, closed without merging